image: maven:3.6-jdk-8

stages:
  - build
  - test-2.11
  - test-2.12
  - deploy

variables:
  MAVEN_CLI_OPTS: "--batch-mode -Dsetl.test.cassandra.host=cassandra -Dsetl.test.postgres.host=postgres -Dsetl.test.dynamodb.host=amazon-dynamodb-local"
  POSTGRES_DB: framework_dev
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  AWS_ACCESS_KEY_ID: fakeAccess
  AWS_SECRET_ACCESS_KEY: fakeSecret
  AWS_REGION: eu-west-1

build:2-11:
  stage: build
  script:
    - mvn clean $MAVEN_CLI_OPTS compile

build:2-12:
  stage: build
  script:
    - rm -rf pom.xml
    - cp dev/pom_2.12.xml pom.xml
    - mvn clean $MAVEN_CLI_OPTS compile

test-2.11:
  stage: test-2.11
  services:
    - cassandra
    - postgres
    - amazon/dynamodb-local
  dependencies:
    - build:2-11
  script:
    - mvn clean $MAVEN_CLI_OPTS test

test-2.12:
  stage: test-2.12
  services:
    - cassandra
    - postgres
    - amazon/dynamodb-local
  dependencies:
    - test-2.11
  script:
    - rm -rf pom.xml
    - cp dev/pom_2.12.xml pom.xml
    - mvn clean $MAVEN_CLI_OPTS test

deploy:snapshot:2-11:
  stage: deploy
  script:
    - mvn clean -DskipTests $MAVEN_CLI_OPTS deploy
  dependencies:
    - test-2.12
  only:
    - master

deploy:snapshot:2-12:
  stage: deploy
  script:
    - rm -rf pom.xml
    - cp dev/pom_2.12.xml pom.xml
    - mvn clean -DskipTests $MAVEN_CLI_OPTS deploy
  dependencies:
    - test-2.12
  only:
    - master

deploy:release:2-11:manual:
  stage: deploy
  script:
    - mvn clean -Dchangelist= -DskipTests $MAVEN_CLI_OPTS deploy
  dependencies:
    - test-2.12
  only:
    - master
  when: manual

deploy:release:2-12:manual:
  stage: deploy
  script:
    - rm -rf pom.xml
    - cp dev/pom_2.12.xml pom.xml
    - mvn clean -Dchangelist= -DskipTests $MAVEN_CLI_OPTS deploy
  dependencies:
    - test-2.12
  only:
    - master
  when: manual

deploy:release:2-11:auto:
  stage: deploy
  script:
    - mvn clean -Dchangelist= -DskipTests $MAVEN_CLI_OPTS deploy
  dependencies:
    - test-2.12
  only:
    - /^v.*$/
  except:
    - branches

deploy:release:2-12:auto:
  stage: deploy
  script:
    - rm -rf pom.xml
    - cp dev/pom_2.12.xml pom.xml
    - mvn clean -Dchangelist= -DskipTests $MAVEN_CLI_OPTS deploy
  dependencies:
    - test-2.12
  only:
    - /^v.*$/
  except:
    - branches
