image: maven:3.6-jdk-8

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn clean compile

test:
  stage: test
  script:
    - export JAVA_TOOL_OPTIONS="-Xmx1024m -Xms1024m"  # solve jvm heap size problem
    - mvn clean test

deploy:snapshot:
  stage: deploy
  script:
    - mvn clean deploy -DskipTests -Pprovided
  dependencies:
    - test
  only:
    - master
  when: manual

deploy:release:
  stage: deploy
  script:
    - mvn -Dchangelist= clean deploy -DskipTests -Pprovided
  dependencies:
    - test
  only:
    - master
  when: manual