image: maven:3.6-jdk-8

stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "--batch-mode"

cache:
  paths:
    - target/

build:
  stage: build
  script:
    - mvn clean $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - export JAVA_TOOL_OPTIONS="-Xmx1024m -Xms1024m"  # solve jvm heap size problem
    - mvn $MAVEN_CLI_OPTS test

deploy:snapshot:
  stage: deploy
  script:
    - mvn -DskipTests -Pprovided $MAVEN_CLI_OPTS deploy
  dependencies:
    - test
  only:
    - master
  when: manual

deploy:release:
  stage: deploy
  script:
    - mvn -Dchangelist= -DskipTests -Pprovided $MAVEN_CLI_OPTS deploy
  dependencies:
    - test
  only:
    - master
  when: manual