stages:
  - test
  - build
  - upload
  - deploy

test:
  stage: test
  image: maven:3.6-jdk-8-alpine
  script:
    - chmod a+x mvnw
    - ./mvnw clean test
  tags:
    - lab

build:lab:
  stage: build
  script:
    - chmod a+x mvnw
    - ./mvnw -Dchangelist=${CHANGELIST} -Drevision=${VERSION} clean package -DskipTests
  artifacts:
    name: dc-spark-core
    paths:
      - target/dc-spark-sdk-${VERSION}${CHANGELIST}.jar
    expire_in: 2 hrs
  tags:
    - lab
  only:
    - master

upload:lab:
  stage: upload
  script:
    - scp -v target/dc-spark-sdk-${VERSION}${CHANGELIST}.jar root@master-dc:/opt/apps/spark/jars/external/gitlab/dc-spark-sdk-${VERSION}${CHANGELIST}.jar
  dependencies:
    - build:lab
  environment:
    name: lab
  tags:
    - lab
  only:
    - master

#Deployment to Nexus SNAPSHOT: the version should be defined in pom
deploy:snapshot:
  stage: deploy
  script:
    - mvn clean deploy -DskipTests -Pprovided
  dependencies:
    - build:lab
  environment:
    name: lab
  tags:
    - lab
  only:
    - master
  when: manual

deploy:release:
  stage: deploy
  script:
    - mvn -Dchangelist= clean deploy -DskipTests -Pprovided
  dependencies:
    - build:lab
  environment:
    name: lab
  tags:
    - lab
  only:
    - master
  when: manual
