image: maven:3.6-jdk-8

stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MVN_CMD_CPT_OPTS: "-Dscala.version=2.11.12 -Dscala.compat.version=2.11"

cache:
  paths:
    - target/

build:latest:
  stage: build
  script:
    - mvn clean $MAVEN_CLI_OPTS compile

build:compatible:
  stage: build
  script:
    - mvn clean $MAVEN_CLI_OPTS $MVN_CMD_CPT_OPTS compile

test:latest:
  stage: test
  dependencies:
    - build:latest
  script:
    - mvn clean $MAVEN_CLI_OPTS test

test:compatible:
  stage: test
  dependencies:
    - build:compatible
  script:
    - mvn clean $MAVEN_CLI_OPTS $MVN_CMD_CPT_OPTS test

deploy:snapshot:
  stage: deploy
  script:
    - mvn clean -DskipTests -Pprovided $MAVEN_CLI_OPTS deploy
  dependencies:
    - test:latest
  only:
    - master

deploy:snapshot-compat:
  stage: deploy
  script:
    - mvn clean -DskipTests -Pprovided $MAVEN_CLI_OPTS $MVN_CMD_CPT_OPTS deploy
  dependencies:
    - test:compatible
  only:
    - master

deploy:release:manual:
  stage: deploy
  script:
    - mvn clean -Dchangelist= -DskipTests -Pprovided $MAVEN_CLI_OPTS deploy
  dependencies:
    - test:latest
  only:
    - master
  when: manual

deploy:release-compat:manual:
  stage: deploy
  script:
    - mvn clean -Dchangelist= -DskipTests -Pprovided $MAVEN_CLI_OPTS $MVN_CMD_CPT_OPTS deploy
  dependencies:
    - test:compatible
  only:
    - master
  when: manual

deploy:release:auto:
  stage: deploy
  script:
    - mvn clean -Dchangelist= -DskipTests -Pprovided $MAVEN_CLI_OPTS deploy
  dependencies:
    - test:latest
  only:
    - /^v.*$/
  except:
    - branches

deploy:release-compat:auto:
  stage: deploy
  script:
    - mvn clean -Dchangelist= -DskipTests -Pprovided $MAVEN_CLI_OPTS $MVN_CMD_CPT_OPTS deploy
  dependencies:
    - test:compatible
  only:
    - /^v.*$/
  except:
    - branches
